apiVersion: v1
kind: Service
metadata:
  name: airosu-server
spec:
  type: LoadBalancer
  selector:
    agones.dev/gameserver: airosu-server
  ports:
  - protocol: UDP
    port: 7777
    targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airosu
  labels:
    app: airosu
spec:
  selector:
    matchLabels:
      app: airosu-server
  template:
    metadata:
      labels:
        app: airosu-server
    spec:
      containers:
      - name: match
        image: brandolau/airosu-server:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100M"
            cpu: "1"
          limits:
            memory: "1G"
            cpu: "2"
        ports:
          - name: match-port
            containerPort: 7777
            protocol: UDP
